### ISSUE TITLE
Refresh DNS host list on retries

### ISSUE THREAD

**Issue by ripienaar** [choria-io/mcollective-choria#129]
At present we feed the DNS host list into the NATS gem and just let it retry for ever, this is fine and works but does not allow for people changing SRV records and such during the lifetime of the daemon.  Those will never be refreshed.

A reworking of things so that we ask the NATS gem to do `n` tries on its own and then bail out will give us the opportunity to requery SRV records every `n` tries thus making the daemon much more resilient to changes in it's environment

**Comment by ripienaar** [comment]
Doing this is actually quite a nightmare, at present while I do maintain a subscriptions list in the mcollective side its not really complete since by design we rely on the client gems to maintain that and resubscribe on reconnect which simplify the code a lot.

The proposed rework would end up with the NATS client not being subscribed at all if we let it fall out of its retry loop so we'd have to build in all that logic on this end.

So it would be good if there was some way for the NATS gem to allow programatic server pool updates which it would try on next retry etc, I asked the NATS gem authors for their thoughts in https://github.com/nats-io/pure-ruby-nats/issues/9

**Comment by helge000** [comment]
I also encountered this issue and would tend to mark it as severe:
 - SRV reords could not be resolved
 - Logs are flooded
 - No way to solve it with the puppet module
 - No way to restart mcollective since chicken and the egg problem

I'd suggest to simply dead fail the service if re - resolving tends to be hard. The next puppet run will restart it, then records are resolved again.

**Comment by ripienaar** [comment]
Yeah I agree, definitely need to look into this one more. I made some inroads already during other PRs so that now I do have a Choria side track of all I need to manage resubscribes on reconnects. So I think what's left is just to rewrite the connect blocks to not inifinite retry in the gem

Had hoped the gem would by now have resolved this problem and given me generic hooks. Alas. I will look at doing this for the next iteration

**Comment by ripienaar** [comment]
I think this is better in the choria daemon, at any rate its at least fixable there, will close this one as its near impossible with how the ruby gem is - and the ruby daemon is not long for the world
