### ISSUE TITLE
check the crl for client certs

### ISSUE THREAD

**Issue by ripienaar** [choria-io/mcollective-choria#26]
puppet agent caches the CRL locally it seems, we should check that and detect revoked certs

**Comment by ripienaar** [comment]
Puppet does not update the CRL, on hold till it does

**Comment by mateusz-gozdek-sociomantic** [comment]
I think it would be nice to still implement it, as it's not a big task and some people (like me) delivers Puppet CRL on it's own. Let's say you have more than one puppetserver, you want to have same CRL everywhere, so revoked clients are not able to connect to any of your puppetservers.
