### ISSUE TITLE
Local gem repo option

### ISSUE THREAD

**Issue by dbnewman** [choria-io/mcollective-choria#260]
Hi,

We are behind a fairly strict firewall/proxy setup, and the GEM downloads are failing the build. Is it possible to specify a local repo of GEM files to build?

**Comment by ripienaar** [comment]
yeah I suspect it is, I think we need to do something like:

```
package{"foo":
  provider => "gem",
  source => "https://your.local.repo"
}
```

does that work with normal puppet package resources? in which case I can add a `gem_source` parameter to the module and use that

**Comment by dbnewman** [comment]
Looks like that would work just fine based on the provider -- https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider/package/gem.rb

**Comment by ripienaar** [comment]
OK, closing in favour of https://github.com/choria-io/puppet-mcollective/issues/98
