### ISSUE TITLE
How to install from Puppetfile via github

### ISSUE THREAD

**Issue by jeefberkey** [choria-io/mcollective-choria#268]
Currently, you have to either use the published module from the forge or download this module and run the `release` rake task to use this module. This is prohibitive for those that like to use r10k with local git repositories, not a forge. 

How would I install this module from git in a Puppetfile?

**Comment by ripienaar** [comment]
The only supported way to install is from the forge modules I am afraid, the main modules I could perhaps find a way to distribute as source - but the many plugins I can't realistically do.  

So it does not seem worth the effort to do it just for these 3 modules when that would not solve the whole problem.

You're only the 2nd person who have asked about this, the other one ended up grabbing the forge sources and hosting on their own git repo

**Comment by jeefberkey** [comment]
That's a decent idea and will do for now, thanks.

**Comment by jeefberkey** [comment]
Where is the source for the `agent` plugins?
* choria/mcollective_agent_puppet
* choria/mcollective_agent_package
* choria/mcollective_agent_service
* choria/mcollective_agent_filemgr
* choria/mcollective_util_actionpolicy

**Comment by ripienaar** [comment]
The repos are at puppetlabs. What's on the forge was built with 'mco plugin package' on stock puppetlabs repos and pushed to forge. 

Maintainership is currently a nightmare and I can't really improve matters without forking them.  Not quite there yet.

**Comment by jeefberkey** [comment]
👍 thanks

**Comment by ripienaar** [comment]
http://choria.io/docs/configuration/plugins/ this here, so you can build your own plugins or theirs and achieve the same outcome
