### ISSUE TITLE
Module config hash documentation

### ISSUE THREAD

**Issue by jeefberkey** [choria-io/mcollective-choria#269]
What parameters are available in: 

* `mcollective_choria::config`
* `mcollective_choria::server_config`
* `mcollective_choria::client_config`

I'm playing around with `ssldir` and am having trouble seeing how these hashes relate to one another.

**Comment by ripienaar** [comment]
these are basically free form, they map to whatever is valid in mcollective config files ie `server.cfg` 

config - all config files
server_config - just server.cfg
client_config - just client.cfg

but same settings

**Comment by jeefberkey** [comment]
Does that mean the only place to set `choria.ssldir` is in Puppet (which translates to /etc/puppetlabs/mcollective/plugin.d/choria.cfg)? I'd like the client and the server to have a different `ssldir`

**Comment by ripienaar** [comment]
that should work yes

**Comment by ripienaar** [comment]
ah its a bit weird, if you want it in the main config - which is what these configs do - you need to try this via hiera:

```
mcollective_choria::config: 
  plugin.choria.ssldir: /foo
```

**Comment by jeefberkey** [comment]
👍 This fixed my issue and got me going. 

I ended up having to use the following:
```
mcollective::server_config:
  plugin.choria.ssldir: /var/lib/choria
mcollective::client_config:
  plugin.choria.ssldir: ~/.choria
```
which has nothing to do with choria

**Comment by ripienaar** [comment]
@jeefberkey glad its sorted, best stick with defaults :) you're likely to have some other issues, I know it can work with custom paths but choria really is for AIO and people who follow convention
