### ISSUE TITLE
Puppet Enterprise Support and Install Instructions

### ISSUE THREAD

**Issue by dpdil** [choria-io/mcollective-choria#270]
Hello, 

Apologies if this is not the correct place to raise this.

1. Is Choria currently supported on Puppet Enterprise?
2. If so, does the standard set of deploy instructions work for PE?

Thanks

**Comment by ripienaar** [comment]
I have not tested it on PE. I would like it to work and for sure I believe Choria's security model is much much better than how PE deploys it but I have not had time to look into that

Would be happy to assist someone who wanted to try it in a lab or something

**Comment by dpdil** [comment]
Ok, great. I've managed to get it working on PE 2016.4 with a linux client and server. I'm just testing on windows now.

**Comment by dpdil** [comment]
It was pretty straight forward and simple. I did run into an issue where there was a conflict with the choria and PE manifest for configuring the clients. Once I had those sussed out and had put the right config into hiera it pretty much worked straight away. The playbook feature is a really killer feature, something that PE currently lacks and I think would help bridge a big gap in the product stack at the moment.

**Comment by ripienaar** [comment]
@dpdil that's pretty great, thanks, guess I'll set up a PE lab and document the process.

If you have any feedback on the playbooks I'd love to hear from you.  I think they're really important but at the same time have not had much feedback from users about them, so as you're using them I'd be keen on feature ideas or general feedback

I'll close this issue, feel free to contact me again here or on the mcollective users list
