### ISSUE TITLE
depenancy on puppetlabs/inifile not defined

### ISSUE THREAD

**Issue by dforste** [choria-io/mcollective-choria#284]
You use ini_setting in several places. the config fails to load with inifile 1.2.0 in fact it wipes out the entire leaving it similar to this: 
```
[]
registerinterval = 10
[]
registerinterval = 10
[]
registerinterval = 10
[]
registerinterval = 10
[]
registerinterval = 10

[]
registration = Choria
```
Should add a dependency on the earliest version where it works. It stops mangling the file with 1.6.0.

**Comment by ripienaar** [comment]
Wow thanks for that. I will see if I can reproduce and pin it. That's unfortunate.

**Comment by ripienaar** [comment]
Closing this, it will not be needed anymore
