### ISSUE TITLE
mcollective_choria::config does not work (as advertised?)

### ISSUE THREAD

**Issue by helge000** [choria-io/mcollective-choria#286]
Trying to save some SRV record setup I wanted to fix the SRV domain lookup:

http://choria.io/docs/deployment/dns/:
```
mcollective_choria::config:
  srv_domain: "prod.example.net"
```

- Just setting this creates file `/etc/puppetlabs/mcollective/plugin.d/.conf` with a single setting.
- Setting up the config file name as well, it created a file `dns.conf`
- Both settings where to no avail

Note: I am using an ENC (foreman). Hira lookup works, though; using Default -> Hira -> ENC (from lowest to highest priority)

**Comment by helge000** [comment]
Off topic: Great module btw, saved me a lot of work setting up mcollective

**Comment by ripienaar** [comment]
Hmm, this works exactly for me:

```
mcollective_choria::config:
  srv_domain: "dev.example.net"
```

```
$ cat /etc/puppetlabs/mcollective/plugin.d/choria.cfg
srv_domain = dev.example.net
```

something else going on :(

**Comment by helge000** [comment]
Maybe it is just the name? Ie, is `choria.cfg` mandatory or does it just load all config files from plugin.d?

**Comment by ripienaar** [comment]
The name matters, if you try to access `plugin.foo.bar` as config item it needs to have been in `plugin.d/foo.cfg`

**Comment by ripienaar** [comment]
Config name comes from https://github.com/choria-io/mcollective-choria/blob/master/module/data/plugin.yaml#L2 so it should not have a problem setting it, unless somehow your data in modules is borked

**Comment by helge000** [comment]
Question: Is there any chance the config file changes? This setting definatly does not work for me at the moment.

If not, we should set this up as default and remove it from hiera (like already done with ports and such). 
I would 'PR this, should you agree.

**Comment by ripienaar** [comment]
No we cant remove it from data, has to be there - this functionality exist in every one of the mcollective plugin modules so it has to work - and does work elsewhere.

Something up locally on your side, maybe a OS with bad data defaults, or foreman setting some setting it shouldnt etc.

I think to get to the bottom of it add some debugging here and see what you see on your side https://github.com/choria-io/puppet-mcollective/blob/master/manifests/module_plugin.pp#L91

**Comment by helge000** [comment]
Maybe I understood wrong: According to docs the configuration point for the config is the `mcollective_choria` module `config` param; we are mixing it with hiera from the top module. 

Shouldn't there be a `config` param on mcollective directly?

**Comment by ripienaar** [comment]
There are 2 places to configure things.

Imagine you have a mco plugin that manages Puppet, it will have configuration for things like where the puppet executable lives.  This is not a mcollective core config so logically you want this to go with the puppet plugin.

Then there are server wide configs for things like logging and just arbitrary random settings you might set.

The first set lives with each plugin module - like mcollective_choria, the second lives with the main mcollective module.

So to configure choria to not use SRV - mcollective has no SRV awareness - you set it in the choria specific module ie mcollective_choria::config

**Comment by ripienaar** [comment]
(continuing other comment)

The mcolective_choria module - or the hypothetical Puppet one - uses a utility define found in the main mcollective module to do the hard work.

Hence you add debugging bits to the `puppet-mcollective` module to see what config this one is setting and if the vars it uses to set the path exist

**Comment by helge000** [comment]
> I think to get to the bottom of it add some debugging here and see what you see on your side https://github.com/choria-io/puppet-mcollective/blob/master/manifests/module_plugin.pp#L91

Could I just use `mcollective::server_config` for the SRV settings? As I read to manifest, all of the configuration goes to plugin.d/choria.conf:
https://github.com/choria-io/puppet-mcollective/blob/master/manifests/module_plugin.pp#L37
https://github.com/choria-io/puppet-mcollective/blob/master/manifests/module_plugin.pp#L100

**Comment by ripienaar** [comment]
you can set `plugin.choria.use_srv` yes, but trust me if this does not work you'll have bigger problems, best to find out whats going on :)

**Comment by helge000** [comment]
Hm, I would file this as *random weirdness, cosmic radiation*. 

Manually setting `mcollective_choria::config_name: choria` via ENC gets me a working config:
```
---
use_srv_records: false
puppetserver_host: foreman.int.m-box.de
puppetserver_port: 8140
middleware_hosts: foreman.int.m-box.de:4222
puppetca_host: foreman.int.m-box.de
puppetca_port: 8140
```

**Comment by ripienaar** [comment]
@helge000 heh ok, am convinced you'll find other things wrong too because this should work, lets see :)

**Comment by helge000** [comment]
Maybe this is because of the way Forman/Enc works. I have to include `mcollective_choria` because I make one setting. 
Normally, I only include the top module's init class (witch in turn looks up all other parameters from this class)

This was why I was asking if there is a way mcollective is exposing choria settings in a way

**Comment by ripienaar** [comment]
@helge000 but if it does not set this parameter via the ENC it will fall back to the data in module, it would be handy to see what the foreman ENC output is when you dont set it - see if it sets it to some blank value

**Comment by helge000** [comment]
Yep, I have no idea. Before closing, I ran:

```
puppet lookup --explain --node foreman.int.m-box.de mcollective_choria::config_name
Searching for "mcollective_choria::config_name"
  Global Data Provider (hiera configuration version 3)
    Using configuration "/etc/puppetlabs/puppet/hiera.yaml"
    Hierarchy entry "yaml"
      Path "/etc/puppetlabs/code/environments/production/hieradata/nodes/foreman.int.m-box.de.yaml"
        Original path: "nodes/%{::trusted.certname}"
        Path not found
      Path "/etc/puppetlabs/code/environments/production/hieradata/common.yaml"
        Original path: "common"
        Path not found
  Module "mcollective_choria" Data Provider (hiera configuration version 5)
    Using configuration "/etc/puppetlabs/code/modules/mcollective_choria/hiera.yaml"
    Hierarchy entry "plugin"
      Path "/etc/puppetlabs/code/modules/mcollective_choria/data/plugin.yaml"
        Original path: "plugin.yaml"
        Found key: "mcollective_choria::config_name" value: "choria"
```
seems right to me

**Comment by ripienaar** [comment]
Yeah - but if the ENC sets this value specifically somehow, Hiera will never be consulted.  That'll break many things

**Comment by helge000** [comment]
Hiera is consulted for all values *not* set via ENC. Eg. mcollective part for this host:

```
  mcollective:
    client: true
    gem_source: http://rubygems.org
    site_policies:
    - action: allow
      actions: "*"
      callers: choria=helge.mcollective
      classes: "*"
      facts: "*"
    - action: allow
      actions: "*"
      callers: choria=foreman-proxy.mcollective
      classes: "*"
      facts: "*"
  nats: 
```

**Comment by ripienaar** [comment]
No idea then :)

**Comment by helge000** [comment]
Yep... me neither. I will raise this issue with the newsgroup.

**Comment by helge000** [comment]
FYI: Just tested again - works now. without setting the parameter. I really have no idea what caused this - thanks for the effort anyway :+1:

**Comment by ripienaar** [comment]
Lol ok glad it works :)
