### ISSUE TITLE
ajcrowe/supervisord dependencies break mcollective_choria installation

### ISSUE THREAD

**Issue by dhollinger** [choria-io/mcollective-choria#308]
The new `ajcrowe/supervisord` dependency requirement has its own dependency on `puppetlabs-concat` < 3.0.0 (a new version of supervisord hasn't been released in over a year). `puppetlabs-concat` has since released both 3.0.0 and 4.0.0 of the module which we use in our environment. 

Due to this requirement, our acceptance tests have broken as another of our dependencies installing `puppetlabs-concat` version 4.0.1 prevents `ajcrowe/supervisord` from installing and, by extension, `choria-mcollective_choria` from installing causing an instant pipeline failure. Additionally as `puppetlabs-concat` 4.x is a major version release, I have no idea if the actual version we have installed via r10k will work with `ajcrowe/supervisord` or not.

Any particular reason that a module that doesn't seem to be maintained anymore became a `choria-mcollective_choria` dependency and what can I do to help rectify this?

**Comment by ripienaar** [comment]
That's unfortunate - @lukebigum wanted to manage the federation broker with supervisord and sent in a PR

Dependencies are just hell and getting worse: soon you will HAVE specify all dependencies. Puppet has no concept of a soft dependency or a suggested dependency

I cannot think of a solution to this other than:

  * make fed broker it's own optional module 
  * try to update supervisord module via a PR

I will do the first option once the new federation + network broker ships which will be soonish hopefully. I also hope to package that properly but will need community help with that for sure. 

What do yous think we can do here to help the situation along?

**Comment by lukebigum** [comment]
That's a pain, I don't enforce dependency checks so I didn't notice this. Looking at the _ajcrowe/supervisord_ code, I don't think there's any reason it can't use the latest _puppetlabs-concat_. There's even a line in the changelog saying "Added support for concat versions >2", but I guess someone forgot the metadata. 

I can send a patch on Monday to bump the dependency to be <= 4.0.0, as long as the minimum is still >=1.0.0 (for any Puppet 3 stragglers out there).  The last merge on _ajcrowe/supervisord_ was a few weeks ago so while it's not using any Puppet 4 syntax it's not completely unmaintained.

For immediate resolution, since it's probably just me using supervisord, I'm happy to remove the dependency from mcollective_choria.

**Comment by dhollinger** [comment]
@lukebigum I was planning on trying that as well, so if you want to bump the concat dependency to <= 5.0.0 (the current is 4.0.1, I believe). I can do it, too. We'll need to try and convince him to release soon.

The issue is that I'm using beaker module install helper, which installs from the forge.... hence the dependency issues. Maybe I move away from that and try to find a way to use 2 fixtures files or our separate tests against both our "production" deps and "upstream" deps

**Comment by ripienaar** [comment]
OK lets see how we get on with updating the supervisord package and if we get nowhere by end next week I do a release that drops the dependency but state it in the docs.

Medium term I will ditch the federation broker here and replace it with a new daemon in go which will be in a different module

Not a long term fix, Puppet will require all dependencies get stated in time but thats some way off.

**Comment by ripienaar** [comment]
One of you are opening a PR yes? I have no supervisord so no way to test if the PR would work etc

**Comment by dhollinger** [comment]
I can since it's just a slight change in the concat dep.

**Comment by lukebigum** [comment]
Now that I actually try push a new Concat I can see that ajcrowe/supervisord is relying on ancient Concat code that it's not just a matter of bumping the metadata and test fixtures.  If I put the effort into doing that, I may as well fork the whole thing and make it Puppet 4 ready, which is a bit of work. For now I've sent in PR #312 to undo the breaking metadata change.

**Comment by ripienaar** [comment]
Thanks @lukebigum yeah this is what I was afraid of and couldn't test on my own, thanks for staying on it.  I'll do a release this week then to get this out

**Comment by ripienaar** [comment]
I'll close this then till we have a better plan, thanks everyone, shall release tomorrow
