### ISSUE TITLE
mco choria request_cert fails when puppet master runs on webrick / rack

### ISSUE THREAD

**Issue by smortex** [choria-io/mcollective-choria#322]
When running puppet from Rack or WEBrick, requesting a certificate for a new user fails:

```
% mco choria request_cert
Encountered a critical error: Failed to fetch CA from puppet:8140: 400: Bad Request
```

This is due to [the `environment` parameter](https://docs.puppet.com/puppet/5.0/http_api/http_certificate_request.html#certificate-request) (required while it is not used) [not being set](https://github.com/choria-io/mcollective-choria/blob/d10be522cef860e6eb84d5d5581ae479827b42f8/lib/mcollective/util/choria.rb#L857) ([same problem here](https://github.com/choria-io/mcollective-choria/blob/d10be522cef860e6eb84d5d5581ae479827b42f8/lib/mcollective/util/choria.rb#L899)).

Also, the HTTP header `Content-Type` does not make sense here, while the `Accept` HTTP header is required:

```
% mco choria request_cert
Encountered a critical error: Failed to fetch CA from puppet:8140: 406: Not Acceptable
```

**Comment by ripienaar** [comment]
awesome, thank you
