### ISSUE TITLE
Add pre_sleep to mcollective task

### ISSUE THREAD

**Issue by dnlsng** [choria-io/mcollective-choria#339]
The mcollective_assert task has a pre_sleep option which is quite useful. However, the mcollective task does not have this same option. This is needed in order to replace all of my old mcollective_assert tasks.

**Comment by ripienaar** [comment]
Good catch thanks will ensure it's in before removing the old.

**Comment by ripienaar** [comment]
@dnlsng Thanks, I made this `pre_sleep` apply to all task types but unlike `mcollective_assert` it defaults to no sleep, seemed to belong there next to `try_sleep` etc
