### ISSUE TITLE
is it possible to use choria with external ca

### ISSUE THREAD

**Issue by schlitzered** [choria-io/mcollective-choria#342]
hey,

i am using the FreeIPA integrated ca to provide certificates for my puppetservers and agents, so the puppet internal ca is disabled. 

since the docs say that choria is relying on the puppetca to issue certificates, i am wondering if there is a way to create all the needed certificates for choria upfront via FreeIPA.

is this possible, and if yes how?

kind regards

**Comment by ripienaar** [comment]
If you put your client certs here:

```
       SSL Directory: /home/rip/.puppetlabs/etc/puppet/ssl (found)
  Client Public Cert: /home/rip/.puppetlabs/etc/puppet/ssl/certs/rip.mcollective.pem (found)
  Client Private Key: /home/rip/.puppetlabs/etc/puppet/ssl/private_keys/rip.mcollective.pem (found)
             CA Path: /home/rip/.puppetlabs/etc/puppet/ssl/certs/ca.pem (found)
            CSR Path: /home/rip/.puppetlabs/etc/puppet/ssl/certificate_requests/rip.mcollective.pem (found)
      Public Cert CN: rip.mcollective (match)
```

and your node certs here:

```
       SSL Directory: /etc/puppetlabs/puppet/ssl (found)
  Client Public Cert: /etc/puppetlabs/puppet/ssl/certs/dev1.devco.net.pem (found)
  Client Private Key: /etc/puppetlabs/puppet/ssl/private_keys/dev1.devco.net.pem (found)
             CA Path: /etc/puppetlabs/puppet/ssl/certs/ca.pem (found)
            CSR Path: /etc/puppetlabs/puppet/ssl/certificate_requests/dev1.devco.net.pem (found)
```

then it will work, you can configure the location of "SSL Directory" but the locations under that has to follow this pattern.

**Comment by ripienaar** [comment]
`mco choria show_config` will validate you got it right for you (it's what you see above)

**Comment by schlitzered** [comment]
wow, thanks for the fast answer.

i will setup a new lab environment to try this out

**Comment by ripienaar** [comment]
ok :) let me know if you need help, the intention that it Just Works for typical Puppet but flexibility is there to get where you need to get.

I'll close this one now, reach out sould you have issues - I suggest the `choria-users` list on google groups for this kind of issues.
