### ISSUE TITLE
Bump supported version of camptocamp-systemd module

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [choria-io/mcollective-choria#351]
Currently, it produces following warning:
```
Warning: Module 'camptocamp-systemd' (v1.0.0) fails to meet some dependencies:
  'choria-mcollective_choria' (v0.3.1) requires 'camptocamp-systemd' (>= 0.3.0 < 1.0.0)
```

However, I didn't notice any problems with version `1.0.0`.

**Comment by ripienaar** [comment]
I am supposing this is down to some other modules you use who have competing dependencies (they need 1)? A clean install at present work for me?

Not against updating anyway so lets do it

**Comment by mateusz-gozdek-sociomantic** [comment]
I just like to keep all modules up to date :) And I'm kind of person who is annoyed by warnings like this.

**Comment by ripienaar** [comment]
yeah fair enough, its a pain in the arse, I try to check out all depedencies every release or 3 but I bet we are about to see a load of releases on modules

thanks as always!
