### ISSUE TITLE
Could not find class ::mcollective_choria

### ISSUE THREAD

**Issue by ttres** [choria-io/mcollective-choria#380]
The Puppet agent fails (RC=1) applying the `mcollective` class, with the following error message:

```bash
# puppet apply -e 'include mcollective'
Warning: ModuleLoader: module 'mcollective' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules
   (file & line not available)
Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::mcollective_choria for puppet.local.bb.com.br at /etc/puppetlabs/code/environments/production/modules/mcollective/manifests/init.pp:77:3 on node puppet.local
```

Modules were installing using r10k (`nats` and `systemd` also):

```yaml
mod 'mcollective',
  :git => 'git@github.com:choria-io/puppet-mcollective.git',
  :tag => '0.3.0'
mod 'mcollective_choria',
  :git => 'git@github.com:choria-io/mcollective-choria.git',
  :tag => '0.5.0'
```

Looks like the `choria` module code is inside the repo, in `module/choria/`, but outside the classloader PATH.

**Comment by ripienaar** [comment]
You have to get the modules from the forge. Via github is simply not possible.

**Comment by ttres** [comment]
Ok, understood.

But getting from Forge is not an option, unfortunately.

**Comment by ripienaar** [comment]
Why not?

**Comment by ttres** [comment]
Corporate internet access restrictions :-o

And our internal proxy, JFrog Artifactory, don't work with r10k, also.

**Comment by ripienaar** [comment]
Ok well I could see how we could fix it for a module but you would have the same problem on every plugin module. So you are SOL I am afraid 

Soon hopefully I might control the plugin situation better and might make a plan for now no luck whatsoever.
