### ISSUE TITLE
Consider splitting out the puppet modules or provide a git subtree automated mirror

### ISSUE THREAD

**Issue by vStone** [choria-io/mcollective-choria#382]
Since we are not using r10k or a puppetfile but are using git submodules to manage our puppet modules, keeping the puppet modules for mcollective/choria is a long and manual process.

**Comment by ripienaar** [comment]
Afraid this will not change for a long time, if ever. 

All the modules for plugins also have this problem and it’s not something that’s easily fixable

I would have to make new repos and during the build process snapshot each module into that. 

The community as a whole and the vendor has been pretty serious about adopting the r10k/puppetfile model so optimising for that seems the right direction

**Comment by KrisBuytaert** [comment]
Not sure what you see but the comunnity has not been adopting r10k/puppetfile that much ,  I only see it at PE customers.

**Comment by ripienaar** [comment]
it's not even that its a matter of splitting the module - the module is effectively a tarball that contains in it all the files, files thats the outcome of a build process.  This is the problem, so during a build/release:

The files are modified for the new version: https://github.com/choria-io/mcollective-choria/blob/master/Rakefile#L30

The files are then copied into the module during a release: https://github.com/choria-io/mcollective-choria/blob/master/Rakefile#L87 based on what the module is interested in distributing

Likewise for the plugin modules, they are built dynamically like a tarball or rpm would be.

You are basically saying "we use cpio to extract all our files from rpms then check them into git, this is the right way to manage systems please cater for us" no, no its not :)

It seems trivially automatable on your end to download a module and untar it over your local version of the repo and just tag it, then you can do what you want

**Comment by vStone** [comment]
We'll never see eye to eye on this I guess ;)

**Comment by ripienaar** [comment]
@vStone hehe, lets chat at cfgmgcamp? I could host a bunch of repos thats the intermediate of these modules for example but you can imagine thats a fair bit of work so lets chat
