### ISSUE TITLE
mco Plugin Time Invalid

### ISSUE THREAD

**Issue by JSP-GIHS** [choria-io/mcollective-choria#454]
Any mco commands apart from local help and choria show_config return no results. Testing this from the local server, and from a dedicated mco client.

According to the choria.log:

```
{"level":"error","msg":"Could not create Request to validate Secure Request with: The JSON body from the SecureRequest is not a valid Request message: Could not validate Request JSON data: Could not validate incoming document: invalid character '-' in numeric literal","time":"2018-03-23T10:56:11+10:30"}
{"level":"error","msg":"Could not cache Client Certificate: The JSON body from the SecureRequest is not a valid Request message: Could not validate Request JSON data: Could not validate incoming document: invalid character '-' in numeric literal","time":"2018-03-23T10:56:11+10:30"}
{"component":"server","identity":"contint01.dev.internal","level":"error","msg":"Could not decode incoming request: SecureRequest message created from the Transport Message did not pass security validation","time":"2018-03-23T10:56:11+10:30"}
```

mco ping debug:

```
debug 2018/03/23 10:56:11: nats.rb:322:in `publish_connected_broadcast' Sending a broadcast message to NATS target '{:name=>"mcollective.broadcast.agent.discovery", :headers=>{"mc_sender"=>"contint01.dev.internal", "reply-to"=>"mcollective.reply.contint01.dev.internal.16103.1"}}' for message type request
```

There are a few references to Time.now throughout the code that may actually need to be Time.now.to_i for this to work. Else, the protocol definition seems to be the problem here:
```
/choria-io/go-protocol
	Line 60: time: integer. Expected to be UTC
```

But I can not find where "time" is being populated for the request to suggest a correction - sorry.

**Comment by ripienaar** [comment]
Hmm something’s gone wrong of you get this. You should not be running `server` that is an eventual replacement for mcollectived- today you need to run choria broker and normal mcollectived which is what these modules would setup for you

I am not sure how anything would have enabled the server service in the modules as they stand

**Comment by JSP-GIHS** [comment]
Configs are pretty raw:
```
  include mcollective

  class { 'nats':
    ensure => 'absent',
  }

  class { 'choria':
    manage_package_repo => true,
  }

  class { 'choria::broker':
    network_broker => true,
  }
```

Hiera:

`mcollective::client: true`

Did I miss something in the upgrade?

**Comment by ripienaar** [comment]
Ok so we probably have a bug where the server service is enabled on Ubuntu by default despite my efforts not to do that 

Have to figure out:

Why is choria-server service running 
Why is mcollective service not running. 

What you have appears to be right

**Comment by JSP-GIHS** [comment]
After a fresh restart of the Ubuntu server, turns out they're both enabled in systemd. I've disabled the choria-server.service (not the choria broker, naturally) and restarted again. Some debugs now out of mcollective which I wasn't getting before (still no pings though):

```
D, [2018-03-23T15:49:11.767362+10:30 #4281] DEBUG -- : natswrapper.rb:214:in `block (2 levels) in subscribe' Received a message on mcollective.broadcast.agent.discovery
D, [2018-03-23T15:49:11.767654+10:30 #4281] DEBUG -- : runnerstats.rb:49:in `received' Incrementing total stat
D, [2018-03-23T15:49:11.767718+10:30 #4281] DEBUG -- : pluginmanager.rb:83:in `[]' Returning cached plugin security_plugin with class MCollective::Security::Choria
D, [2018-03-23T15:49:11.768162+10:30 #4281] DEBUG -- : choria.rb:445:in `block in cache_client_pubcert' Already have a cert from choria=administrator.mcollective in /etc/puppetlabs/puppet/ssl/choria_security/public_certs/administrator.mcollective.pem
D, [2018-03-23T15:49:11.768870+10:30 #4281] DEBUG -- : runnerstats.rb:43:in `unvalidated' Incrementing unvalidated stat
W, [2018-03-23T15:49:11.768954+10:30 #4281]  WARN -- : runner.rb:206:in `rescue in block in receiver_thread' Failed to handle message: Received an invalid signature in message from choria=administrator.mcollective - MCollective::SecurityValidationFailed

W, [2018-03-23T15:49:11.768998+10:30 #4281]  WARN -- : runner.rb:207:in `rescue in block in receiver_thread' /opt/puppetlabs/mcollective/plugins/mcollective/security/choria.rb:225:in `validrequest?'
        /opt/puppetlabs/mcollective/plugins/mcollective/security/choria.rb:132:in `decode_request'
        /opt/puppetlabs/mcollective/plugins/mcollective/security/choria.rb:104:in `decodemsg'
        /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/message.rb:187:in `decode!'
        /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/runner.rb:230:in `receive'
        /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/runner.rb:189:in `block in receiver_thread'
        /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/runner.rb:187:in `loop'
        /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/runner.rb:187:in `receiver_thread'
        /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/runner.rb:142:in `block in start_receiver_thread'
```
Is that signature validation message related to the client certificate, or the message itself? The client certificate is existing, not generated post- "choria/choria" upgrade.

**Comment by ripienaar** [comment]
Ok so we have one big where the server service is enabled. It shouldn’t be. I will verify that and deal with it

Mco seems fine at least it communicates. It’s strange there is no hint about why it’s invalid perhaps make sure /etc/puppetlabs/puppet/ssl/choria_security/public_certs/administrator.mcollective.pem on those node matches the one on your client

**Comment by JSP-GIHS** [comment]
Alright this just got weird:

I regenerated the administrator.mcollective certificate and I cleaned out the choria_security/public_certs. This seemed to resolve it on the server.

Moved to a second server and it did not resolve it. Clearing out the choria_security/public_certs did not fix the issue - until I also restarted the mcollective service.

Unfortunately, because I misread your last path, I changed two things at once (regenerated the certificate on puppet server AND cleaned out choria_security/public_certs) and don't know which of the two resolved it. Based on a brief test now, removing the cached certificate isn't enough, nor is just restarting the service - both are necessary. However, I do not know if both are necessary because of the certificate regeneration.

What's really strange is I have an alternate mcollective certificate (jenkins.mcollective) which doesn't seem to mind if the cache is wrong, so long as the mcollective service was restarted. Server http03 is ping'able from jenkins, but not from administrator. It only becomes pingable after an mcollective restart, but administrator seems to be a special case.

Very strange, but at least I'm functioning for now.

**Comment by ripienaar** [comment]
I can not think of any caching thats being done on the certs - so a restart should not cause this, lots of *should*s this morning though :)

Regarding the jenkins, are you saying that with the cert signed by a wrong CA now you can continue to talk to mco as the jenkins user? or after a different public key being used? That would be a huge bug

**Comment by ripienaar** [comment]
In https://github.com/choria-io/puppet-choria/issues/45 I made it so that the choria-server service will be stopped, you can run master of that repo as a module if you like to try it

**Comment by JSP-GIHS** [comment]
I think I know what happened actually, less concerning than it was:

- administrator.mcollective and jenkins.mcollective generated (Nats installed)
- nats removed, choria::broker installed
- for some reason, both mcollective and choria-server running. Something goes wrong.
- choria-server disabled, system restarted (note: mcollective restarts here)
- mco ping doesn't work. Debugging ensues.
- regenerate administrator.mcollective certificate.
- mco ping still doesn't work. Realise my mistake, remove cache
- mco ping works

For the remote systems, I think there's two things in play:

1. mcollective service needs a restart to re-connect to the new broker topology. When we're testing, the timeframes are too short - if there's a built in re-connect timer for mcollective, I haven't triggered it yet.
2. Because I incorrectly regenerated administrator.mcollective, the remote systems have the wrong PEM in cache for administrator.mcollective

Because I've restarted mcollective on the remote systems, the untampered jenkins.mcollective is still operational, where the regenerated certificate is (correctly) out-of-sync with the cache.

That leaves us with the two questions which are probably answered by the choria service being forcibly stopped by default.

1. How did choria-server get started: Modified in [choria-io/puppet-choria#45](https://github.com/choria-io/puppet-choria/issues/45)
2. Why did the administrator.mcollective certificate need cache clearing on the contint01 server (puppetserver) before it would respond to ping, when the jenkins.mcollective certificate did not.

My guess to number 2 is that something was off with the choria-server part - because I didn't actually test with the jenkins.mcollective certificate at that time, there's no reason it would have been impacted.

**Comment by ripienaar** [comment]
Choria server starts by default. Bloody Debian policy rubbish - by their policies I should start broker by default too. I might change it and start nothing by default like any sane person would do against Debian policy. But for now the fix in the module will get us to a good place. 

For the certs. It’s hard to say. The certs once they exist are only read. Choria server and mcollective runs fine against the same cert cache (I do this) so for me with both problems I don’t have issues. Hard to guess what happened with yours. Though I guess both could attempt to cache at the same time and there is a race that you triggered?

The certs are such that they are written once and once only. Never again even if you present a new named one that differs. It won’t write it. This avoids spoofing and some attacks. If you regenerate a cert you have to manually (or with some automation) go remove it everywhere. This is safest. 

So given that - I can’t imagine how the scenario you describe exist but perhaps I am not following you 100%

**Comment by JSP-GIHS** [comment]
It is definitely safest, and a good choice.

Besides, that's why we've got puppet bolt :)
