### ISSUE TITLE
choria broken in Puppet 5.5

### ISSUE THREAD

**Issue by law** [choria-io/mcollective-choria#455]
New nodes do not register their full Fact profile with Puppet 5.5.  mcollective.log displays: 

`E, [2018-03-25T02:26:21.176208-07:00 #1288] ERROR -- : yaml_facts.rb:35:in 'rescue in block in load_facts_from_source' Failed to load yaml facts from /etc/puppetlabs/mcollective/generated-facts.yaml: Psych::BadAlias: Unknown alias: 1`

even though the fact shows up in facter: 
[02:28:45 root@mainsite01:/var/log/puppetlabs] # facter -p agent_specified_environment
staging

mco does not pick it up: 
```
law@runner01:~$ /opt/puppetlabs/bin/mco ping -W 'role::mainsite'
mainsite01.mycorp.lan                    time=34.14 ms
mainsite02.mycorp.lan                    time=34.62 ms
mainsite03.mycorp.lan                    time=35.04 ms
mainsite03.staging.mycorp.lan            time=35.47 ms
mainsite02.staging.mycorp.lan            time=37.75 ms
mainsite01.staging.mycorp.lan            time=40.72 ms


---- ping statistics ----
6 replies max: 40.72 min: 34.14 avg: 36.29 
law@runner01:~$ 
law@runner01:~$ /opt/puppetlabs/bin/mco ping -W 'role::mainsite agent_specified_environment=staging'
mainsite01.staging.mycorp.lan            time=39.10 ms


---- ping statistics ----
1 replies max: 39.10 min: 39.10 avg: 39.10 
law@runner01:~$ 

```

This is Puppet 5.5, on Ubuntu 16.04, using Choria module version 0.1.0 and mcollective_choria module version 0.6.0.

**Comment by antaflos** [comment]
This was reported in https://tickets.puppetlabs.com/browse/MCO-833 as well.

**Comment by ripienaar** [comment]
work around in https://github.com/choria-io/puppet-mcollective/issues/163
