### ISSUE TITLE
Enable the ability to change discovery method on tasks

### ISSUE THREAD

**Issue by dhollinger** [choria-io/mcollective-choria#458]
Enable the use of the `--dm` option on the command line with `mco tasks`

**Comment by ripienaar** [comment]
This is specifically disabled to keep the UI from being so completely cluttered like every other mco thing is:

https://github.com/choria-io/mcollective-choria/blob/7fda1819a392459199222e2241b6212e2915430a/lib/mcollective/application/tasks.rb#L25

But it's a bit too much, so I have to decide to either just put in discovery method support or clutter the UI, will have to do some tests and see how things look
