### ISSUE TITLE
choria SSL auth uses runner's certs when run via `sudo -u`

### ISSUE THREAD

**Issue by matt-cahill** [choria-io/mcollective-choria#459]
You may want to push me back on this one (as intended behaviour) in which case I'll ask theforeman for an improvement to enable sudo-less mcollective support.

This is the main crux of the issue
```
sysadmin@puppet:/usr/share/foreman-proxy$ sudo -u foreman-proxy /opt/puppetlabs/bin/mco find

The find application failed to run, use -v for full error backtrace details: No such file or directory @ rb_sysopen - /home/sysadmin/.puppetlabs/etc/puppet/ssl/certs/foreman-proxy.mcollective.pem
```

This may seem like an unusual way to invoke `mco` but for puppetrun support Foreman uses the following code:

https://github.com/theforeman/smart-proxy/blob/develop/modules/puppet_proxy_mcollective/mcollective_main.rb

Either running `mco` as root by default or as a configured user using sudo for impersonation. Adding "-i" allows the sudo command to work correctly but ideally I'd set that user's shell to /bin/false which would preclude that.

I believe the line in question is here:

https://github.com/choria-io/mcollective-choria/blob/7fda1819a392459199222e2241b6212e2915430a/lib/mcollective/util/choria.rb#L666

I'm not sure if it's possible to get the home dir of the running user rather than expanding `~` from the environment?

**Comment by ripienaar** [comment]
The problem is of course to ensure what I do differently is cross platform and work everywhere.  I do not really have the man power to do that myself so I rely on the ruby project who have many more eyes to do so...thus use their library.

It is annoying that the HOME is needed and this has tripped me up plenty as well.  But that's probably hints there, you you just need to arrange for HOME to be set correctly this is probably something you can arrange sudo do for you? otherwise `sudo -u foo HOME=/home/foo mco find` might even be enough?

**Comment by matt-cahill** [comment]
Hi sorry for the delay getting back to you. 

Yes that works and is more satisfactory than using "sudo -i", you can close this as it currently works in the same way as other commands e.g. `sudo -u foo ls -al ~`
I'll make a pull request to the foreman with some additional code to pull the user's home directory and set up the sudo environment.

Thanks for your help!

cheers

Matt

**Comment by ripienaar** [comment]
great, glad that's sorted then let me know if you need anything else

**Comment by matt-cahill** [comment]
I submitted this pull request to foreman smart-proxy https://github.com/theforeman/smart-proxy/pull/572

out of interest changing https://github.com/choria-io/mcollective-choria/blob/7fda1819a392459199222e2241b6212e2915430a/lib/mcollective/util/choria.rb#L666

to
```
File.expand_path("~%s/.puppetlabs/etc/puppet/ssl" % [env_fetch("USER", @config.identity)])
```
also resolves the issue. Would you like me to submit that pr to your repo too?

cheers

Matt

**Comment by ripienaar** [comment]
Seems to just be shifting the deck chairs - now another variable is needed for it to work :)

I am not sure why `@config.identity` would substitute here, since identity is the hostname (usually FQDN) of the node it's on.

Further windows does not have USER it has USERNAME.

It's just way too complex to try do this right in a cross platform manner.  It's a 400 line C implementation for good reason - it's really complex :)

**Comment by matt-cahill** [comment]
Windows is already taken out of the equation three lines above in the elsif statement though, so that line would only apply to non-windows clients not running as root if I understand correctly?

I see your point about @config.identity (sorry I pulled that quickly from the certname function) so perhaps it should be this which will fall back to the original line if $USER isn't present.

```
File.expand_path("~%s/.puppetlabs/etc/puppet/ssl" % env_fetch("USER"))
```

The expand_path docs state that "~user" will expand to the home directory of "user" so it seems like a valid cross platform change to me.

https://ruby-doc.org/core-1.9.3/File.html#method-c-expand_path

**Comment by ripienaar** [comment]
yeah, OK I guess this is safe enough, if USER isnt set it will just fall back to what we have today, you can make a PR if you wish

**Comment by matt-cahill** [comment]
Will do this as soon as I can, apologies for the delay.

**Comment by matt-cahill** [comment]
@ripienaar Thanks for your help and patience on this. I stumbled across the fact that this is the effect of a different sudo default in ubuntu compared with other distros.
Setting `Defaults env_keep -= "HOME"` in `/etc/sudoers` gives the desired behaviour in this case.
Obviously no point in introducing code changes that can be resolved by other means so I'll close this again.

cheers

Matt

**Comment by ripienaar** [comment]
@matt-cahill hehe ok, well either way I am not against it to make the general out of the box experience better - but this is already kind of out of my space as its a foreman script thing

thanks anyway!
