### ISSUE TITLE
Running tasks with no parameters fails

### ISSUE THREAD

**Issue by dnlsng** [choria-io/mcollective-choria#472]
When running a task that has no required parameters, the command fails.
```
# mco tasks run myapp::task -I /foo/
Could not parse input from --input as YAML or JSON
```

**Comment by ripienaar** [comment]
Can you share the plan? or at least the parameters part of it?

```puppet
plan acme::simple (
) {
  notice("hello world")
}
```


```
% mco playbook run acme::simple
Notice: Scope(<module>/acme/plans/simple.pp, 3): hello world

Plan acme::simple ran in 0.02 seconds: OK
```

**Comment by dnlsng** [comment]
Playbooks are fine. It's when i'm running a puppet task.

**Comment by ripienaar** [comment]
ah wow, i need more coffee lol sorry about that

**Comment by ripienaar** [comment]
https://github.com/choria-io/mcollective-choria/blob/97b4424c467c95ceb8208417d461183de207eb1e/lib/mcollective/util/tasks_support/cli.rb#L161-L163

This should just return {} instead of failing

**Comment by dnlsng** [comment]
I tried running the task without the `unless result.empty?` and it works fine with no parameters.
