### ISSUE TITLE
Enable batches on tasks

### ISSUE THREAD

**Issue by cdeering** [choria-io/mcollective-choria#487]
Having the ability to run Tasks in batches would be extremely useful.  Would be nice to be able to have long batch sleep times (15 min?) and run the batches in the background.  "mco tasks" doesn't seem to have a background option where "mco rpc bolt_tasks" does.

**Comment by ripienaar** [comment]
background it cant do no, it'll have to be on the CLI for now.

All for adding batches though on the CLI in line with `mco rpc`

Curious, what's the use case for a 15 minute sleep, that seems very long so I am just curious

**Comment by ripienaar** [comment]
Got this going, including background.  Still curious about your 15 minute sleep use case @cdeering

**Comment by cdeering** [comment]
The extended sleep period is for cases like system updates and reboots.  I know of a few other cases where the process I need run can take 10 or 15 minutes and this use of tasks has so many advantages.

**Comment by ripienaar** [comment]
ok thanks :)
