### ISSUE TITLE
expose task name and id to the running task

### ISSUE THREAD

**Issue by ripienaar** [choria-io/mcollective-choria#498]
We should add some hints to the environment that tasks can use:

```
_task=foo::bar # in line with what bolt will do
_task_id=xxxxxxx
_task_caller=rip.mcollective
```

Any others you can think of @cdeering?

**Comment by cdeering** [comment]
No, I think that should cover it.

**Comment by ripienaar** [comment]
OK I've added this, I am not going to document it since this is basically building the Puppet Inc spec and they have added the `_task` to the spec recently, relying on the others will make this a choria forked feature which I am not too keen on 

So this will just be a little bit extra I guess, not really great
