### ISSUE TITLE
Future of choria development

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [choria-io/mcollective-choria#521]
I just read changelog for latest `puppet-agent` release, and I noticed, that mcollective is now deprecated. See https://puppet.com/docs/puppet/5.5/release_notes_agent.html#puppet-agent-554. This leads to a question of how the future development of choria project will look like in this case. Are you planning to adopt mcollective entirely maybe?

**Comment by ripienaar** [comment]
The Choria server will replace mcollectived. The mcollective code will be stripped down a lot - basically just the RPC, config and a few utils- and shipped as a gem

Once agent 6 is a bit clearer I will go ahead and make that gem - the existing mcollective-client would even do but I don’t control that one. 

With choria server out a few months now along with its MCO RPC compatibility layer  - and actively tested by quite a few users I am confident this is a good approach. 

This will actually give me some freedom to make bigger changes I wanted to the mco layer so it’s all good.

**Comment by mateusz-gozdek-sociomantic** [comment]
OK, so `choria-server` will replace mcollective daemon/server and mco client will be shipped with gem. Will it support for all plugins as old mco?

**Comment by mateusz-gozdek-sociomantic** [comment]
OK, then I think there is nothing to worry about. I hope the migration will be straight-forward when the time comes :) Thanks a lot for explanation!

**Comment by ripienaar** [comment]
@mateusz-gozdek-sociomantic thats the hope, many moving parts though, more testers always welcome as I am already making much of the 6 tooling available today
