### ISSUE TITLE
choria::discover at_least => 0 results in err

### ISSUE THREAD

**Issue by khaefeli** [choria-io/mcollective-choria#590]
I've the following code to discover new nodes, where I don't know the `$fqdn` yet:

```
$range = range(0,19)
 $range.each | $x | {
   $result = choria::discover('mcollective',
     at_least => 0,
     discovery_method => mc,
     #test => true,
     facts => ["fqdn=/${node}.*/"],
   )
   if $result.empty { notice("no result") }
   else { notice("test 123") }
 }
```
this results in `Error: Evaluation Error: Error while evaluating a Function Call, Did not discover any nodes for nodeset task_nodes` if discover doesn't find any node and stops the execution of the plan. 

expected output: empty `$result` and exit code 0

**Comment by ripienaar** [comment]
@khaefeli are you in a position to test the small patch in the associated PR?

It ads a new property `empty_ok` to all discovery types that avoid the error from being raised when set to true

**Comment by khaefeli** [comment]
@ripienaar works like a charm. Thank you!
