### ISSUE TITLE
Puppet 6.6: Cannot execute Bolt tasks as the node does not meet the minimum compatability requirements

### ISSUE THREAD

**Issue by khaefeli** [choria-io/mcollective-choria#592]
Puppet AIO 6.6 renamed the task wrapper to execution wrapper: https://github.com/puppetlabs/pxp-agent/commit/eb3ab563a17cef32efed3e9a69d56a3e38194b94

This results in an error during task runs:
`mco tasks run mcollective_agent_bolt_tasks::ping --message "Hello"`

`Cannot execute Bolt tasks as the node does not meet the minimum compatability requirements`

**Comment by ripienaar** [comment]
As a test you can set data like this:

https://github.com/choria-io/mcollective-choria/blob/4fefe905163faae9745a2dcae977a98610e83947/module/choria/data/FreeBSD.yaml#L2-L3

This will both let you tell us if it still work and get you going quicker :)

wanna give it a go?

**Comment by khaefeli** [comment]
@ripienaar: thanks, I've did a workaround with a symlink. But this is obviously the better solution.
Set the path in `puppet_aio/6.yaml` and it's working fine now.

**Comment by jay7x** [comment]
Hit into same issue with puppet 6 (agent 6.9.0, server 6.6.0). Fixed by adding wrapper path as below:
```
mcollective_choria::config:
  tasks.wrapper_path: /opt/puppetlabs/puppet/bin/execution_wrapper
```
