### ISSUE TITLE
PuppetDB SRV port overwritten by default port

### ISSUE THREAD

**Issue by Wiston999** [choria-io/mcollective-choria#593]
Hi, seems that due to that line https://github.com/choria-io/mcollective-choria/blob/master/lib/mcollective/util/choria.rb#L618, the port for puppetdb used in SRV record is not being taking into account, I have effectively setup a SRV record with non standard port 
```
$ dig +short srv _x-puppet-db._tcp.mydomain.com
0 5 9141 db.puppet.mydomain.com.
```
but, when running `mco choria show_config` I get 
```
...
     PuppetDB Server: puppet.mydomain.com:8081
...
```
I guess that a workaround can be to explicitly setup puppetDB port using hiera like the following snippet:
```
mcollective_choria::config:
  puppetdb_port: 9141
```

**Comment by ripienaar** [comment]
ah, hmm, so i have to somehow know which of the 2 SRV records won, thats annoying but I guess not impossible.

Thanks will fix
