### ISSUE TITLE
playbook --loglevel doesn't match up with puppet

### ISSUE THREAD

**Issue by vjanelle** [choria-io/mcollective-choria#600]
The puppet loglevels are at https://puppet.com/docs/puppet/5.5/metaparameter.html#loglevel

* emerg
* alert
* crit
* err
* warning
* notice
* info
* verbose
* debug

https://github.com/choria-io/mcollective-choria/blob/6c317878ec3b14e7c4928ff20a1c556f974a63ab/lib/mcollective/application/playbook.rb#L100 Validates with the wrong set of values.

**Comment by vjanelle** [comment]
@ripienaar should these align with puppet, or do you want the mcollective ones to map to the puppet ones?

**Comment by ripienaar** [comment]
thank you
