### ISSUE TITLE
Default length for single queried facts is too short

### ISSUE THREAD

**Issue by guillemlc** [choria-io/mcollective-choria#625]
We found the 40 character  validation for facts to be too short, as some hashed facts may go easily beyond that.

```The facts application failed to run: Cannot validate input fact: Input string is longer than 40 character(s)

Cannot validate input fact: Input string is longer than 40 character(s) (MCollective::DDLValidationError)
```
---
Also we tried modifying in the DLL:

```action "get_fact", :description => "Retrieve a single fact from the fact store" do
     display :always

     input :fact,
           :prompt      => "The name of the fact",
           :description => "The fact to retrieve",
           :type        => :string,
           :validation  => '^[\w\-\.]+$',
           :optional    => false,
           :maxlength   => 40
```
choria-mcorpc-support-2.20.8/lib/mcollective/agent/rpcutil.ddl

Changing the maxlength value there seems to have no effect. If I set anything that would fit in my string, like 50, 60, 70, it would always complain about it being larger than 40.

Where can we properly set that maxlength?

Thank you

**Comment by ripienaar** [comment]
If you want to send a PR to this repo where I moved the issue to now for the 2 files that'd be great, if its urgent I can do a small release

**Comment by ripienaar** [comment]
Resolved in https://github.com/choria-io/mcollective-choria/pull/627
