### ISSUE TITLE
Registration plugin mcollective/registration/choria.rb missing, mcollective will not start

### ISSUE THREAD

**Issue by sshipway** [choria-io/mcollective-choria#632]
After upgrading the module (finally) to 0.17.3 from 0.5 I find that new hosts can no longer install, as they complain about the registration plugin.

A puppet run complains
```
error 2020/08/11 03:50:52: pluginmanager.rb:171:in `rescue in loadclass' Failed to load Mcollective::Registration::Choria: cannot load such file -- mcollective/registration/choria.rb
```

Starting mcollective fails:
```
Aug 11 03:47:57 au3avs02.smxemail.com systemd[1]: Starting The Marionette Collective...
Aug 11 03:47:57 au3avs02.smxemail.com mcollectived[11443]: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/pluginmanager.rb:169:in `load': cannot load such file -- mcollective/registration/choria.rb (LoadError)
Aug 11 03:47:57 au3avs02.smxemail.com mcollectived[11443]: from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/pluginmanager.rb:169:in `loadclass'
Aug 11 03:47:57 au3avs02.smxemail.com mcollectived[11443]: from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/config.rb:167:in `loadconfig'
Aug 11 03:47:57 au3avs02.smxemail.com mcollectived[11443]: from /opt/puppetlabs/puppet/bin/mcollectived:57:in `<main>'
Aug 11 03:47:57 au3avs02.smxemail.com systemd[1]: mcollective.service: control process exited, code=exited status=1
Aug 11 03:47:57 au3avs02.smxemail.com systemd[1]: Failed to start The Marionette Collective.
Aug 11 03:47:57 au3avs02.smxemail.com systemd[1]: Unit mcollective.service entered failed state.
Aug 11 03:47:57 au3avs02.smxemail.com systemd[1]: mcollective.service failed.
```

Looking in the filesystem and module, I see that `lib/mcollective/registration/choria.rb` is indeed missing, though it used to be present, and is still present on my previously-deployed hosts.

What am I doing wrong, and why is this file no longer deployed even though mcollective seems unable to start without it?

**Comment by ripienaar** [comment]
What should have happened is that the old mcollectived should not be running anymore and now you should be running choria server - mcollectived has not been supported for a long time. 

What version puppet are you on? Only Puppet 6 and newer is supported.

**Comment by sshipway** [comment]
We're on puppet server 6.12.0 now, though the agents are still 5.5.21 until the servers are stable.  I upgraded all the puppet mcollective modules to the latest version supported (they were on a very old 0.5 version previously).  So, which modules should replace the existing mcollective, mcollecitve_agent*, etc modules?  Are the same parameters compatible between the modules?  There doesn't seem to be any documentation I could find covering what we're doing.
As long as mco continues to work things should be OK, it is used by gitlab to trigger r10k and deploy configurations to all the puppetmasters.

**Comment by ripienaar** [comment]
Minimal agent version we support is 6

That’s because Puppet stopped shipping mcollective with puppet 6 and the modules now function for that world and only configure choria server. 

Some background here:

https://choria.io/blog/post/2018/12/01/puppet6-support/

And I think this is the latest versions you can run with your setup

https://choria.io/blog/post/2019/05/27/releases/

**Comment by sshipway** [comment]
Thanks for this info - I'll look at updating our mcollective install to choria now we're on puppet6, but it looks like a big job

**Comment by ripienaar** [comment]
In general moving to choria from mco just works, with the main missing feature being -S searches.

but your nodes need puppet 6, not just the puppet server

**Comment by ripienaar** [comment]
fixed this elsewhere
