### ISSUE TITLE
Prepare for mcollective::service removal

### ISSUE THREAD

**Issue by smortex** [choria-io/mcollective-choria#638]
The `mcollective::service` class is being removed from the mcollective module https://github.com/choria-io/puppet-mcollective/pull/276.

Some adjustments are required in this repository to cope with it.

* [x] ~~#639 Workaround for unbreaking discovery~~ (abandoned)
* [x] #640 Allow discovery with choria::service
* [x] https://github.com/choria-io/puppet-mcollective/pull/277 Revert server facts removal

**Comment by ripienaar** [comment]
Hmm, this is not good, will need to make a plan with that - I will probably have to make the server facts work again or write a new fact that picks this up from choria somehow.

Need to have a thing, for now I'll merge the one that just makes it work again and keep this open

**Comment by ripienaar** [comment]
good stuff

**Comment by ripienaar** [comment]
@smortex anything else here or can i close this one?

**Comment by smortex** [comment]
I think we are good.  Thanks!
